# Arithmeic functions

# Shuffle

In [8]:
import numpy as np
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 1 2 5 4]


# unique

In [11]:
var1=np.array([1,2,3,4,2,5,2,6,2,7])

x=np.unique(var1)
y=np.unique(var1,return_index=True,return_counts=True)

print(x)
print(y)

[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


In [15]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten 

In [21]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y.flatten())
print("flatten",y.flatten(order="F"))
print("ravel",np.ravel(y,order="F"))
print(y.flatten(order="A"))
print(y.flatten(order="K"))

[1 2 3 4 5 6]
flatten [1 3 5 2 4 6]
ravel [1 3 5 2 4 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Inserting data into array

In [29]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(x.dtype)
print(type(x))
new_a=np.insert(x,2,40)
print(new_a)
new_1=np.insert(x,(2,4),40)
print(new_1)

[1 2 3 4]
int32
<class 'numpy.ndarray'>
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]


In [38]:
var1=np.array([[1,2,3],[4,5,6]])
y=np.insert(var1,2,6,axis=0)
print(y)
print()
z=np.insert(var1,2,[22,23,24],axis=0)
print(z)
w=np.append(var1,6.5)
print(w)
print()
a=np.append(var1,[(45,44,23)],axis=0)
print(a)

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]
[1.  2.  3.  4.  5.  6.  6.5]

[[ 1  2  3]
 [ 4  5  6]
 [45 44 23]]


# Delete

In [39]:
a=np.array([1,2,3,4])
b=np.delete(a,1)
print(b)

[1 3 4]
