# Copy and view in arrays

In [4]:
import numpy as np
var=np.array([1,2,3,4])
co=var.copy()
var[1]=40
print(var)
print()
print("copy",co)

[ 1 40  3  4]

copy [1 2 3 4]


In [7]:
x=np.array([9,8,7,6,5])
vi=x.view()
x[1]=40
print("x",x)
print("view",vi)

x [ 9 40  7  6  5]
view [ 9 40  7  6  5]


# Join and split in arrays

In [8]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])

z=np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


In [17]:
import numpy as np
a=np.array([[1,2,3],[1,1,2]])
b=np.array([[4,5,6],[7,8,9]])

c=np.concatenate((a,b),axis=0)
print(c)
print()
d=np.concatenate((a,b),axis=1)
print(d)

[[1 2 3]
 [1 1 2]
 [4 5 6]
 [7 8 9]]

[[1 2 3 4 5 6]
 [1 1 2 7 8 9]]


In [21]:
a=np.array([[1,2],[1,1]])
b=np.array([[4,5],[7,8]])

c=np.stack((a,b),axis=0)
print(c)
print()
d=np.stack((a,b),axis=1)
print(d)


[[[1 2]
  [1 1]]

 [[4 5]
  [7 8]]]

[[[1 2]
  [4 5]]

 [[1 1]
  [7 8]]]


In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b),axis=0)
print(c)
print()
d=np.stack((a,b),axis=1)
print(d)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))#row
d=np.vstack((a,b))#col
e=np.dstack((a,b))#height
print(c)
print()
print(d)
print()
print(e)
print()

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]



# split the array

In [30]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
print(var1)
print()
ar=np.array_split(var1,3)
print(ar)
print(type(ar))
print(ar[0])
print(ar[1])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]
[3 4]


In [40]:
import numpy as np
var2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var2)
print()
ar1=np.array_split(var2,3)
print(ar1)
print(type(ar1))
print(ar1[0])
print(ar1[1])
ar2=np.array_split(var2,3,axis=1)
print(ar2)
print()
ar3=np.array_split(var2,3,axis=0)
print(ar3)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
<class 'list'>
[[1 2 3]]
[[4 5 6]]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

