In [1]:
import numpy as np

var=np.array([1,2,3])

print("data type",var.dtype)

data type int32


In [3]:
import numpy as np

var=np.array(["a","p","i"])

print("data type",var.dtype)

data type <U1


In [4]:
import numpy as np

var=np.array(["a",1,"i"])

print("data type",var.dtype)

data type <U11


# changing data type

In [7]:
x=np.array([1,2,3,4],dtype=np.int8)
print("data type",x.dtype)
print(x)

data type int8
[1 2 3 4]


In [9]:
x1=np.array([11,12,13,14],dtype="f")
print("data type",x1.dtype)
print(x1)

data type float32
[11. 12. 13. 14.]


In [11]:
x2=np.array([11,12,13,14])

new=np.float32(x2)
print("data type",x2.dtype)
print(x2)
print(new)
print("data type",new.dtype)

data type int32
[11 12 13 14]
[11. 12. 13. 14.]
data type float32


In [13]:
x2=np.array([11,12,13,14])

new=np.float32(x2)

new_one=np.int_(new)

print("data type",x2.dtype)
print(x2)
print(new)
print("data type",new.dtype)
print(new_one)
print("data type",new_one.dtype)

data type int32
[11 12 13 14]
[11. 12. 13. 14.]
data type float32
[11 12 13 14]
data type int32


In [18]:
x3=np.array([1,2,3,4])

new_1=x3.astype(bool)

print(x3)
print(new_1)

[1 2 3 4]
[ True  True  True  True]


In [2]:
import numpy as np

var=np.array([1.2,2.5,3.0])

print("data type",var.dtype)

data type float64
