# Indexing and slicing in arrays

# indexing

In [1]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(x[-2])
print(x[2])

[1 2 3 4]
3
3


In [10]:
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.shape)
print(var1.ndim)
print()
print(var1[0][2])

[[9 8 7]
 [4 5 6]]
(2, 3)
2

7


In [17]:
var2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var2)
print(var2.ndim)
print(var2[0][1][1])
print(var2[1][0][1])



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
4
6


# Slicing

In [26]:
import numpy as np
x=np.array([1,2,3,4,5,6])
#           0,1,2,3,4,5
print(x)
print("2 to 5",x[1:5])
print("1 to 4",x[0:4])
print("2 to end",x[1:])
print("start to 5",x[:5])
print("stop:",x[:5:2])


[1 2 3 4 5 6]
2 to 5 [2 3 4 5]
1 to 4 [1 2 3 4]
2 to end [2 3 4 5 6]
start to 5 [1 2 3 4 5]
stop: [1 3 5]


In [35]:
var1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print(var1.ndim)
print(var1.shape)
print()
print("8 to 5",var1[1,1:])
print("8 to 6",var1[1,1:4])
print("12 to 15",var1[2,1:])


[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2
(3, 5)

8 to 5 [8 7 6 5]
8 to 6 [8 7 6]
12 to 15 [12 13 14 15]
