# iteration in arrays

In [3]:
import numpy as np
x=[9,8,7,6,5,4,3]
print(x)
print()
for i in x:
    print(i)

[9, 8, 7, 6, 5, 4, 3]

9
8
7
6
5
4
3


In [5]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()

for j in var:
    print(j)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]


In [7]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()

for k in var:
    for l in k:
      print(l)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [9]:
var1=np.array([[[1,2],[3,4],[5,6]]])
print(var1)
print(var1.ndim)
for i in var1:
    for j in i:
        for k in j:
            print(k)

[[[1 2]
  [3 4]
  [5 6]]]
3
1
2
3
4
5
6


In [11]:
var2=np.array([1,2,3],ndmin=4)
print(var2)
for i in var2:
    for j in i:
        for k in j:
            for l in k:
                print(l)

[[[[1 2 3]]]]
1
2
3


# function for iteration

In [17]:
import numpy as np

var1 = np.array([[[1, 2], [3, 4], [5, 6]]])
for i in np.nditer(var1, flags=['buffered'], op_dtypes=['S']):
    print(i)


b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [19]:
import numpy as np

var1 = np.array([[[1, 2], [3, 4], [5, 6]]])
for i,d in np.ndenumerate(var1):
    print(i,d)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 5
(0, 2, 1) 6


In [20]:
import numpy as np

var1 = np.array([[1, 2], [3, 4]])
for i,d in np.ndenumerate(var1):
    print(i,d)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
