# Matrix in numpy arrays

In [3]:
import numpy as np

var=np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [4]:
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [8]:
var1=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[1,2]])

print(var1+var2)
print(var1*var2)
print(var1.dot(var2))

[[2 4]
 [2 4]]
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [10]:
var1=np.array([[1,2],[1,2]])
var2=np.array([[1,2],[1,2]])
print(var1*var2)

[[1 4]
 [1 4]]


# Matrix functions

# Transpose

In [14]:
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print()

print(np.transpose(x))
print()
print(x.T)
print()
print(np.swapaxes(x,0,1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [15]:
y=np.matrix([[1,2],[3,4]])
print(y)
print()
print(np.swapaxes(y,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# Inverse

In [16]:
y=np.matrix([[1,2],[3,4]])
print(y)
print()
print(np.linalg.inv(y))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
z=np.matrix([[1,2,3],[3,4,5]])
print(z)
print()
print(np.linalg.inv(z))
# only for square matrix

[[1 2 3]
 [3 4 5]]



LinAlgError: Last 2 dimensions of the array must be square

# power of matrix

In [20]:
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
# identity matrix
print(np.linalg.matrix_power(a,0))
print()
# inverse ki power
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# Determinant of matrix

In [23]:
x=np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(np.linalg.det(x))
# only for square matrix

0.0
