# Search in array

In [3]:
import numpy as np

var=np.array([1,2,3,4,2,5,2,5,6,7])
#             0,1,2,3,4,5,6,7,8,9

x=np.where( var==2 )
y=np.where((var%2)==0)

print(x)
print(y)

(array([1, 4, 6], dtype=int64),)
(array([1, 3, 4, 6, 8], dtype=int64),)


# search sorted array

In [11]:
var1=np.array([1,2,3,4,7,8,9])
#              0,1,2,3,4,5,6,7
var2=np.searchsorted(var1,[5,6,7])
print(var2)
var3=np.searchsorted(var1,9)
print(var3)

[4 4 4]
6


# sort array

In [12]:
x=np.array([1,22,3,9,7])

print(np.sort(x))

[ 1  3  7  9 22]


In [14]:
y=np.array(["a","s","c","b","d"])

print(np.sort(y))

['a' 'b' 'c' 'd' 's']


In [15]:
a=np.array([[100,22],[39,9],[7,8]])

print(np.sort(a))

[[ 22 100]
 [  9  39]
 [  7   8]]


# Filter array

In [17]:
var1=np.array([1,2,3,4,5])

filter=[True,False,True,True,False]

new_a=var1[filter]
print(new_a)
print(type(new_a))

[1 3 4]
<class 'numpy.ndarray'>
