# aritmetic operations on arrays

In [4]:
import numpy as np

vara=np.array([1,2,3])
varb=np.array([4,5,6])

varadd=vara+varb
print(varadd)

[5 7 9]


In [5]:
vara=np.array([1,2,3])
varb=np.array([4,5,6])

varsub=varb-vara
print(varsub)


[3 3 3]


In [11]:
vara=np.array([2,98,3])
varb=np.array([4,5,6])

varmultiply=varb%vara
print(varmultiply)

[0 5 0]


In [19]:
vara=np.array([2,9,3])
varb=np.array([4,5,6])

varrec=np.reciprocal(vara)
print(varrec)

[0 0 0]


# 2d array

In [20]:
vara=np.array([[2,9,3],[2,5,4]])
varb=np.array([[4,5,6],[7,8,9]])

varadd=np.add(vara,varb)
print(varadd)

[[ 6 14  9]
 [ 9 13 13]]


# 3d array

In [22]:
vara=np.array([[[2,9,3],[2,5,4],[7,8,9]]])
varb=np.array([[[4,5,6],[7,8,9],[1,2,3]]])
print(vara)
print(varb)

varpow=vara**varb
print(varpow)

[[[2 9 3]
  [2 5 4]
  [7 8 9]]]
[[[4 5 6]
  [7 8 9]
  [1 2 3]]]
[[[    16  59049    729]
  [   128 390625 262144]
  [     7     64    729]]]


In [26]:
vara=np.array([1,2,3],ndmin=10)
print(vara)
print(vara.ndim)
varsub=np.subtract(vara,1)
print(varsub)

[[[[[[[[[[1 2 3]]]]]]]]]]
10
[[[[[[[[[[0 1 2]]]]]]]]]]


In [27]:
vara=np.array([1,2,3],ndmin=10)
print(vara)

varrec=np.reciprocal(vara)
print(varrec)

[[[[[[[[[[1 2 3]]]]]]]]]]
[[[[[[[[[[1 0 0]]]]]]]]]]


In [30]:
import numpy as np

var=np.array([1,2,3,4,5,6,7,8,1,2])
print("min",np.min(var))
print("max",np.max(var))
print("sqrt",np.sqrt(var))
print("argmin",np.argmin(var))
print("argmax",np.argmax(var))
print("sqrt",np.sqrt(var))

min 1
max 8
sqrt [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 1.         1.41421356]
argmin 0
argmax 7
sqrt [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 1.         1.41421356]


In [31]:
vara=np.array([30,45,60,90])

print(np.sin(vara))
print(np.cos(vara))

[-0.98803162  0.85090352 -0.30481062  0.89399666]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362]


In [36]:
var1=np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis=0))


[2 1 3]


In [39]:
var2=np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.tan(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


In [40]:
var3=np.array([4,5,6])
print(np.cumsum(var3))

[ 4  9 15]


# shape and reshaping in array

In [43]:
import numpy as np
var1=np.array([[1,2,3,4],[1,2,3,4]])

print(var1)
print()
print(var1.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [47]:
var2=np.array([1,2,3],ndmin=4)
print(var2.ndim)
print(var2.shape)

4
(1, 1, 1, 3)


# reshape

In [57]:
var2=np.array([1,2,3,4,5,6,1,2,3])
x=var2.reshape(3,3)
print(x)
print(x.ndim)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2
(3, 3)


In [65]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
x1=var3.reshape(2,3,2)
print(x1.ndim)
print(x1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [66]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
x1=var3.reshape(2,3,2)
print(x1.ndim)
print(x1)
print()
one=x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# broadcasting

In [74]:
import numpy as np

var1=np.array([1,2,3])
print(var1)
print()
print(var1.shape)
var2=np.array([[1],[2],[3]])
print()
print(var2)
print(var2.ndim)
print(var2.shape)
print()
print(var1+var2)

[1 2 3]

(3,)

[[1]
 [2]
 [3]]
2
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [82]:
x=np.array([[2],[3]])
print(x)
print(x.shape)
print(x.ndim)
print()
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(y.shape)
print(y.ndim)
print()
print(x+y)

[[2]
 [3]]
(2, 1)
2

[[1 2 3]
 [4 5 6]]
(2, 3)
2

[[3 4 5]
 [7 8 9]]
